 protoc \                             
  --go_out=internal/ports/grpc \
  --go-grpc_out=internal/ports/grpc \
  --go_opt=paths=source_relative \
  --go-grpc_opt=paths=source_relative \
  proto/patient_records.proto