// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/patient_records.proto

package grpcport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VitalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Systolic      float32                `protobuf:"fixed32,2,opt,name=systolic,proto3" json:"systolic,omitempty"`
	Diastolic     float32                `protobuf:"fixed32,3,opt,name=diastolic,proto3" json:"diastolic,omitempty"`
	HeartRate     float32                `protobuf:"fixed32,4,opt,name=heart_rate,json=heartRate,proto3" json:"heart_rate,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VitalsRequest) Reset() {
	*x = VitalsRequest{}
	mi := &file_proto_patient_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VitalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VitalsRequest) ProtoMessage() {}

func (x *VitalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VitalsRequest.ProtoReflect.Descriptor instead.
func (*VitalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_patient_records_proto_rawDescGZIP(), []int{0}
}

func (x *VitalsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *VitalsRequest) GetSystolic() float32 {
	if x != nil {
		return x.Systolic
	}
	return 0
}

func (x *VitalsRequest) GetDiastolic() float32 {
	if x != nil {
		return x.Diastolic
	}
	return 0
}

func (x *VitalsRequest) GetHeartRate() float32 {
	if x != nil {
		return x.HeartRate
	}
	return 0
}

func (x *VitalsRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *VitalsRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PatientId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientId) Reset() {
	*x = PatientId{}
	mi := &file_proto_patient_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientId) ProtoMessage() {}

func (x *PatientId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientId.ProtoReflect.Descriptor instead.
func (*PatientId) Descriptor() ([]byte, []int) {
	return file_proto_patient_records_proto_rawDescGZIP(), []int{1}
}

func (x *PatientId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PatientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	HasDiabetes   bool                   `protobuf:"varint,3,opt,name=has_diabetes,json=hasDiabetes,proto3" json:"has_diabetes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientInfo) Reset() {
	*x = PatientInfo{}
	mi := &file_proto_patient_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientInfo) ProtoMessage() {}

func (x *PatientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientInfo.ProtoReflect.Descriptor instead.
func (*PatientInfo) Descriptor() ([]byte, []int) {
	return file_proto_patient_records_proto_rawDescGZIP(), []int{2}
}

func (x *PatientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PatientInfo) GetHasDiabetes() bool {
	if x != nil {
		return x.HasDiabetes
	}
	return false
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_patient_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patient_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_patient_records_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_patient_records_proto protoreflect.FileDescriptor

const file_proto_patient_records_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/patient_records.proto\"\xc7\x01\n" +
	"\rVitalsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1a\n" +
	"\bsystolic\x18\x02 \x01(\x02R\bsystolic\x12\x1c\n" +
	"\tdiastolic\x18\x03 \x01(\x02R\tdiastolic\x12\x1d\n" +
	"\n" +
	"heart_rate\x18\x04 \x01(\x02R\theartRate\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\x1b\n" +
	"\tPatientId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\vPatientInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12!\n" +
	"\fhas_diabetes\x18\x03 \x01(\bR\vhasDiabetes\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2m\n" +
	"\x0ePatientRecords\x12/\n" +
	"\fAppendVitals\x12\x0e.VitalsRequest\x1a\x0f.StatusResponse\x12*\n" +
	"\x0eGetPatientInfo\x12\n" +
	".PatientId\x1a\f.PatientInfoB-Z+vitals-service/internal/ports/grpc;grpcportb\x06proto3"

var (
	file_proto_patient_records_proto_rawDescOnce sync.Once
	file_proto_patient_records_proto_rawDescData []byte
)

func file_proto_patient_records_proto_rawDescGZIP() []byte {
	file_proto_patient_records_proto_rawDescOnce.Do(func() {
		file_proto_patient_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_patient_records_proto_rawDesc), len(file_proto_patient_records_proto_rawDesc)))
	})
	return file_proto_patient_records_proto_rawDescData
}

var file_proto_patient_records_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_patient_records_proto_goTypes = []any{
	(*VitalsRequest)(nil),  // 0: VitalsRequest
	(*PatientId)(nil),      // 1: PatientId
	(*PatientInfo)(nil),    // 2: PatientInfo
	(*StatusResponse)(nil), // 3: StatusResponse
}
var file_proto_patient_records_proto_depIdxs = []int32{
	0, // 0: PatientRecords.AppendVitals:input_type -> VitalsRequest
	1, // 1: PatientRecords.GetPatientInfo:input_type -> PatientId
	3, // 2: PatientRecords.AppendVitals:output_type -> StatusResponse
	2, // 3: PatientRecords.GetPatientInfo:output_type -> PatientInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_patient_records_proto_init() }
func file_proto_patient_records_proto_init() {
	if File_proto_patient_records_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_patient_records_proto_rawDesc), len(file_proto_patient_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_patient_records_proto_goTypes,
		DependencyIndexes: file_proto_patient_records_proto_depIdxs,
		MessageInfos:      file_proto_patient_records_proto_msgTypes,
	}.Build()
	File_proto_patient_records_proto = out.File
	file_proto_patient_records_proto_goTypes = nil
	file_proto_patient_records_proto_depIdxs = nil
}
